apiVersion: app.sealos.io/v1
kind: Instance
metadata:
  name: fireboom-cnjuyrcg
  labels:
    cloud.sealos.io/deploy-on-sealos: fireboom-cnjuyrcg
spec:
  gitRepo: https://github.com/fireboomio
  templateType: inline
  categories:
    - low-code
  defaults:
    app_name:
      type: string
      value: fireboom-cnjuyrcg
    app_host:
      type: string
      value: qqytfauu
    app_host1:
      type: string
      value: ezbkmiuv
  inputs: {}
  title: Fireboom
  url: https://fireboom.cloud/
  author: Sealos
  description: >-
    Fireboom is a visualization API cloud platform designed for developers with
    the goal of rapidly delivering production-ready APIs.
  readme: >-
    https://cdn.jsdelivr.net/gh/fireboomio/product-manual@main/kuai-su-ru-men/kuai-su-shang-shou/README.md
  icon: https://avatars.githubusercontent.com/u/117984167?s=200&v=4
  deployCount: 1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fireboom-cnjuyrcg
  annotations:
    originImageName: >-
      fireboomapi/fireboom_server@sha256:27ff832760dec9cf205f02b3516ad6663fa7cbfcf35da1b49196acd00efb598f
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: fireboom-cnjuyrcg
    app: fireboom-cnjuyrcg
    cloud.sealos.io/deploy-on-sealos: fireboom-cnjuyrcg
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: fireboom-cnjuyrcg
  selector:
    matchLabels:
      app: fireboom-cnjuyrcg
  template:
    metadata:
      labels:
        app: fireboom-cnjuyrcg
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      containers:
        - name: fireboom-cnjuyrcg
          image: >-
            fireboomapi/fireboom_server@sha256:27ff832760dec9cf205f02b3516ad6663fa7cbfcf35da1b49196acd00efb598f
          command: []
          args:
            - dev
          resources:
            requests:
              cpu: 100m
              memory: 102Mi
              ephemeral-storage: 200Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
              ephemeral-storage: 200Mi
          ports:
            - containerPort: 9991
              name: api
            - containerPort: 9123
              name: console
          imagePullPolicy: Always
          volumeMounts:
            - name: vn-fbservervn-store
              mountPath: /fbserver/store
            - name: vn-fbservervn-upload
              mountPath: /fbserver/upload
            - name: vn-rootvn-vn-cache
              mountPath: /root/.cache
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /fbserver/store
          value: '1'
        name: vn-fbservervn-store
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        annotations:
          path: /fbserver/upload
          value: '1'
        name: vn-fbservervn-upload
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        annotations:
          path: /root/.cache
          value: '1'
        name: vn-rootvn-vn-cache
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: fireboom-cnjuyrcg
  labels:
    cloud.sealos.io/app-deploy-manager: fireboom-cnjuyrcg
    cloud.sealos.io/deploy-on-sealos: fireboom-cnjuyrcg
spec:
  ports:
    - name: api
      port: 9991
    - name: console
      port: 9123
  selector:
    app: fireboom-cnjuyrcg

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fireboom-cnjuyrcg-qqytfauu
  labels:
    cloud.sealos.io/app-deploy-manager: fireboom-cnjuyrcg
    cloud.sealos.io/app-deploy-manager-domain: qqytfauu
    cloud.sealos.io/deploy-on-sealos: fireboom-cnjuyrcg
  annotations:
    higress.io/response-header-control-remove: X-Frame-Options
    higress.io/response-header-control-update: >
      Content-Security-Policy "default-src * blob: data: *.sealoshzh.site
      sealoshzh.site; img-src * data: blob: resource: *.sealoshzh.site
      sealoshzh.site; connect-src * wss: blob: resource:; style-src 'self'
      'unsafe-inline' blob: *.sealoshzh.site sealoshzh.site resource:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: *.sealoshzh.site
      sealoshzh.site resource: *.baidu.com *.bdstatic.com; frame-src 'self'
      *.sealoshzh.site sealoshzh.site mailto: tel: weixin: mtt: *.baidu.com;
      frame-ancestors 'self' https://sealoshzh.site https://*.sealoshzh.site"

      X-Xss-Protection "1; mode=block"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: >
      more_clear_headers "X-Frame-Options:";

      more_set_headers "Content-Security-Policy: default-src * blob: data:
      *.sealoshzh.site sealoshzh.site; img-src * data: blob: resource:
      *.sealoshzh.site sealoshzh.site; connect-src * wss: blob: resource:;
      style-src 'self' 'unsafe-inline' blob: *.sealoshzh.site sealoshzh.site
      resource:; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:
      *.sealoshzh.site sealoshzh.site resource: *.baidu.com *.bdstatic.com;
      frame-src 'self' *.sealoshzh.site sealoshzh.site mailto: tel: weixin: mtt:
      *.baidu.com; frame-ancestors 'self' https://sealoshzh.site
      https://*.sealoshzh.site";

      more_set_headers "X-Xss-Protection: 1; mode=block";

      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: qqytfauu.sealoshzh.site
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: fireboom-cnjuyrcg
                port:
                  number: 9123
  tls:
    - hosts:
        - qqytfauu.sealoshzh.site
      secretName: wildcard-cert

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fireboom-cnjuyrcg-ezbkmiuv
  labels:
    cloud.sealos.io/app-deploy-manager: fireboom-cnjuyrcg
    cloud.sealos.io/app-deploy-manager-domain: ezbkmiuv
    cloud.sealos.io/deploy-on-sealos: fireboom-cnjuyrcg
  annotations:
    higress.io/response-header-control-remove: X-Frame-Options
    higress.io/response-header-control-update: >
      Content-Security-Policy "default-src * blob: data: *.sealoshzh.site
      sealoshzh.site; img-src * data: blob: resource: *.sealoshzh.site
      sealoshzh.site; connect-src * wss: blob: resource:; style-src 'self'
      'unsafe-inline' blob: *.sealoshzh.site sealoshzh.site resource:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: *.sealoshzh.site
      sealoshzh.site resource: *.baidu.com *.bdstatic.com; frame-src 'self'
      *.sealoshzh.site sealoshzh.site mailto: tel: weixin: mtt: *.baidu.com;
      frame-ancestors 'self' https://sealoshzh.site https://*.sealoshzh.site"

      X-Xss-Protection "1; mode=block"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: >
      more_clear_headers "X-Frame-Options:";

      more_set_headers "Content-Security-Policy: default-src * blob: data:
      *.sealoshzh.site sealoshzh.site; img-src * data: blob: resource:
      *.sealoshzh.site sealoshzh.site; connect-src * wss: blob: resource:;
      style-src 'self' 'unsafe-inline' blob: *.sealoshzh.site sealoshzh.site
      resource:; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:
      *.sealoshzh.site sealoshzh.site resource: *.baidu.com *.bdstatic.com;
      frame-src 'self' *.sealoshzh.site sealoshzh.site mailto: tel: weixin: mtt:
      *.baidu.com; frame-ancestors 'self' https://sealoshzh.site
      https://*.sealoshzh.site";

      more_set_headers "X-Xss-Protection: 1; mode=block";

      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ezbkmiuv.sealoshzh.site
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: fireboom-cnjuyrcg
                port:
                  number: 9991
  tls:
    - hosts:
        - ezbkmiuv.sealoshzh.site
      secretName: wildcard-cert

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: fireboom-cnjuyrcg
  labels:
    cloud.sealos.io/app-deploy-manager: fireboom-cnjuyrcg
    cloud.sealos.io/deploy-on-sealos: fireboom-cnjuyrcg
spec:
  data:
    url: https://qqytfauu.sealoshzh.site
  displayType: normal
  icon: https://avatars.githubusercontent.com/u/117984167?s=200&v=4
  name: Fireboom
  type: iframe
