apiVersion: app.sealos.io/v1
kind: Instance
metadata:
  name: excalidraw-cykalcla
  labels:
    cloud.sealos.io/deploy-on-sealos: excalidraw-cykalcla
spec:
  gitRepo: https://github.com/excalidraw/excalidraw
  templateType: inline
  categories:
    - tool
  defaults:
    app_host:
      type: string
      value: excalidraw-tvapisyq
    app_name:
      type: string
      value: excalidraw-cykalcla
  inputs: {}
  title: Excalidraw
  url: https://excalidraw.com/
  author: Sealos
  description: >-
    An open source virtual hand-drawn style whiteboard. Collaborative and
    end-to-end encrypted.
  readme: https://cdn.jsdelivr.net/gh/excalidraw/excalidraw@master/README.md
  icon: https://avatars.githubusercontent.com/u/59452120?s=48&v=4
  deployCount: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw-cykalcla
  annotations:
    originImageName: >-
      excalidraw/excalidraw@sha256:36cd9a135e25b17e7e0b1b1d64df5fc1dad651eac72b6f2aa9c1d5401eddc68f
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: excalidraw-cykalcla
    app: excalidraw-cykalcla
    cloud.sealos.io/deploy-on-sealos: excalidraw-cykalcla
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: excalidraw-cykalcla
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: excalidraw-cykalcla
    spec:
      automountServiceAccountToken: false
      containers:
        - name: excalidraw-cykalcla
          image: >-
            excalidraw/excalidraw@sha256:36cd9a135e25b17e7e0b1b1d64df5fc1dad651eac72b6f2aa9c1d5401eddc68f
          resources:
            requests:
              cpu: 10m
              memory: 6Mi
            limits:
              cpu: 100m
              memory: 64Mi
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          volumeMounts: []
      volumes: []

---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw-cykalcla
  labels:
    cloud.sealos.io/app-deploy-manager: excalidraw-cykalcla
    cloud.sealos.io/deploy-on-sealos: excalidraw-cykalcla
spec:
  ports:
    - port: 80
  selector:
    app: excalidraw-cykalcla

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: excalidraw-cykalcla
  labels:
    cloud.sealos.io/app-deploy-manager: excalidraw-cykalcla
    cloud.sealos.io/app-deploy-manager-domain: excalidraw-tvapisyq
    cloud.sealos.io/deploy-on-sealos: excalidraw-cykalcla
  annotations:
    higress.io/response-header-control-remove: X-Frame-Options
    higress.io/response-header-control-update: >
      Content-Security-Policy "default-src * blob: data: *.sealoshzh.site
      sealoshzh.site; img-src * data: blob: resource: *.sealoshzh.site
      sealoshzh.site; connect-src * wss: blob: resource:; style-src 'self'
      'unsafe-inline' blob: *.sealoshzh.site sealoshzh.site resource:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: *.sealoshzh.site
      sealoshzh.site resource: *.baidu.com *.bdstatic.com; frame-src 'self'
      *.sealoshzh.site sealoshzh.site mailto: tel: weixin: mtt: *.baidu.com;
      frame-ancestors 'self' https://sealoshzh.site https://*.sealoshzh.site"

      X-Xss-Protection "1; mode=block"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: >
      more_clear_headers "X-Frame-Options:";

      more_set_headers "Content-Security-Policy: default-src * blob: data:
      *.sealoshzh.site sealoshzh.site; img-src * data: blob: resource:
      *.sealoshzh.site sealoshzh.site; connect-src * wss: blob: resource:;
      style-src 'self' 'unsafe-inline' blob: *.sealoshzh.site sealoshzh.site
      resource:; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:
      *.sealoshzh.site sealoshzh.site resource: *.baidu.com *.bdstatic.com;
      frame-src 'self' *.sealoshzh.site sealoshzh.site mailto: tel: weixin: mtt:
      *.baidu.com; frame-ancestors 'self' https://sealoshzh.site
      https://*.sealoshzh.site";

      more_set_headers "X-Xss-Protection: 1; mode=block";

      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: excalidraw-tvapisyq.sealoshzh.site
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: excalidraw-cykalcla
                port:
                  number: 80
  tls:
    - hosts:
        - excalidraw-tvapisyq.sealoshzh.site
      secretName: wildcard-cert

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: excalidraw-cykalcla
  labels:
    cloud.sealos.io/app-deploy-manager: excalidraw-cykalcla
    cloud.sealos.io/deploy-on-sealos: excalidraw-cykalcla
spec:
  data:
    url: https://excalidraw-tvapisyq.sealoshzh.site
  displayType: normal
  icon: https://avatars.githubusercontent.com/u/59452120?s=48&v=4
  name: Excalidraw
  type: iframe
