apiVersion: app.sealos.io/v1
kind: Instance
metadata:
  name: blossom-phzdtkdy
  labels:
    cloud.sealos.io/deploy-on-sealos: blossom-phzdtkdy
spec:
  gitRepo: https://github.com/blossom-editor/blossom
  templateType: inline
  categories:
    - tool
  defaults:
    app_name:
      type: string
      value: blossom-phzdtkdy
    app_host:
      type: string
      value: mppbihsl
  inputs: {}
  title: blossom
  url: https://github.com/blossom-editor/blossom
  author: Sealos
  description: Blossom 是一个支持私有部署的云端双链笔记软件，你可以将你的笔记，图片，个人计划安排保存在自己的服务器中，并在任意设备之间实时同步。
  readme: https://cdn.jsdelivr.net/gh/blossom-editor/blossom@dev/README.md
  icon: >-
    https://cdn.jsdelivr.net/gh/blossom-editor/blossom@dev/blossom-editor/src/renderer/src/assets/imgs/blossom_logo.png
  deployCount: 3

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    sealos-db-provider-cr: blossom-phzdtkdy-mysql
    app.kubernetes.io/instance: blossom-phzdtkdy-mysql
    app.kubernetes.io/managed-by: kbcli
    cloud.sealos.io/deploy-on-sealos: blossom-phzdtkdy
  name: blossom-phzdtkdy-mysql

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blossom-phzdtkdy
  annotations:
    originImageName: jasminexzzz/blossom:1.16.0
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: blossom-phzdtkdy
    app: blossom-phzdtkdy
    cloud.sealos.io/deploy-on-sealos: blossom-phzdtkdy
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: blossom-phzdtkdy
  selector:
    matchLabels:
      app: blossom-phzdtkdy
  template:
    metadata:
      labels:
        app: blossom-phzdtkdy
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      containers:
        - name: blossom-phzdtkdy
          image: jasminexzzz/blossom:1.16.0
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blossom-phzdtkdy-mysql-conn-credential
                  key: password
            - name: SPRING_DATASOURCE_URL
              value: >-
                jdbc:mysql://blossom-phzdtkdy-mysql-mysql..svc:3306/blossom?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&allowMultiQueries=true&useSSL=false&&serverTimezone=GMT%2B8
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: PROJECT_IAAS_BLOS_DOMAIN
              value: https://mppbihsl.sealoshzh.site/pic/
            - name: PROJECT_IAAS_BLOS_DEFAULT-PATH
              value: /home/bl/img/
          resources:
            requests:
              cpu: 100m
              memory: 204Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          ports:
            - containerPort: 9999
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-homevn-bl
              mountPath: /home/bl
          livenessProbe:
            httpGet:
              path: /sys/alive
              port: 9999
            initialDelaySeconds: 300
            periodSeconds: 300
            timeoutSeconds: 300
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /home/bl
          value: '1'
        name: vn-homevn-bl
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: blossom-phzdtkdy
  labels:
    cloud.sealos.io/app-deploy-manager: blossom-phzdtkdy
    cloud.sealos.io/deploy-on-sealos: blossom-phzdtkdy
spec:
  ports:
    - port: 9999
  selector:
    app: blossom-phzdtkdy

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blossom-phzdtkdy
  labels:
    cloud.sealos.io/app-deploy-manager: blossom-phzdtkdy
    cloud.sealos.io/app-deploy-manager-domain: mppbihsl
    cloud.sealos.io/deploy-on-sealos: blossom-phzdtkdy
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1g
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
      rewrite ^/$ /editor/#/settingindex redirect;
spec:
  rules:
    - host: mppbihsl.sealoshzh.site
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: blossom-phzdtkdy
                port:
                  number: 9999
  tls:
    - hosts:
        - mppbihsl.sealoshzh.site
      secretName: wildcard-cert

---
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  finalizers:
    - cluster.kubeblocks.io/finalizer
  labels:
    clusterdefinition.kubeblocks.io/name: apecloud-mysql
    clusterversion.kubeblocks.io/name: ac-mysql-8.0.30
    cloud.sealos.io/deploy-on-sealos: blossom-phzdtkdy
  name: blossom-phzdtkdy-mysql
spec:
  affinity:
    nodeLabels: {}
    podAntiAffinity: Preferred
    tenancy: SharedNode
    topologyKeys: []
  clusterDefinitionRef: apecloud-mysql
  clusterVersionRef: ac-mysql-8.0.30
  componentSpecs:
    - componentDefRef: mysql
      monitor: true
      name: mysql
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 51Mi
      serviceAccountName: blossom-phzdtkdy-mysql
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 3Gi
            storageClassName: openebs-backup
  terminationPolicy: Delete
  tolerations: []

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    sealos-db-provider-cr: blossom-phzdtkdy-mysql
    app.kubernetes.io/instance: blossom-phzdtkdy-mysql
    app.kubernetes.io/managed-by: kbcli
    cloud.sealos.io/deploy-on-sealos: blossom-phzdtkdy
  name: blossom-phzdtkdy-mysql
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    sealos-db-provider-cr: blossom-phzdtkdy-mysql
    app.kubernetes.io/instance: blossom-phzdtkdy-mysql
    app.kubernetes.io/managed-by: kbcli
    cloud.sealos.io/deploy-on-sealos: blossom-phzdtkdy
  name: blossom-phzdtkdy-mysql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: blossom-phzdtkdy-mysql
subjects:
  - kind: ServiceAccount
    name: blossom-phzdtkdy-mysql

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: blossom-phzdtkdy
  labels:
    cloud.sealos.io/app-deploy-manager: blossom-phzdtkdy
    cloud.sealos.io/deploy-on-sealos: blossom-phzdtkdy
spec:
  data:
    url: https://mppbihsl.sealoshzh.site
  displayType: normal
  icon: >-
    https://raw.githubusercontent.com/blossom-editor/blossom/dev/blossom-editor/src/renderer/src/assets/imgs/blossom_logo.png
  name: blossom-phzdtkdy
  type: iframe

---
apiVersion: batch/v1
kind: Job
metadata:
  name: blossom-phzdtkdy-init
  labels:
    cloud.sealos.io/deploy-on-sealos: blossom-phzdtkdy
spec:
  completions: 1
  template:
    spec:
      containers:
        - name: mysql-init
          image: docker.io/arey/mysql-client:latest
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: blossom-phzdtkdy-mysql-conn-credential
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blossom-phzdtkdy-mysql-conn-credential
                  key: password
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: blossom-phzdtkdy-mysql-conn-credential
                  key: host
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: blossom-phzdtkdy-mysql-conn-credential
                  key: port
          command:
            - /bin/sh
            - '-c'
            - >
              echo "CREATE DATABASE blossom DEFAULT CHARACTER SET utf8mb4
              COLLATE utf8mb4_bin;" > /create.sql

              until mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER
              -p$MYSQL_PASSWORD -e 'source /create.sql;' &>/dev/null; do sleep
              1; done
      restartPolicy: Never
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
