apiVersion: app.sealos.io/v1
kind: Instance
metadata:
  name: crmeb-ywnvlics
  labels:
    cloud.sealos.io/deploy-on-sealos: crmeb-ywnvlics
spec:
  gitRepo: https://github.com/crmeb/CRMEB
  templateType: inline
  categories:
    - tool
  defaults:
    app_host:
      type: string
      value: crmeb-wyruqrnp
    app_name:
      type: string
      value: crmeb-ywnvlics
  inputs: {}
  title: CRMEB
  url: https://www.crmeb.com/
  author: Sealos
  description: CRMEB开源商城系统PHP版
  readme: https://cdn.jsdelivr.net/gh/crmeb/CRMEB@refs/heads/master/README.md
  icon: https://www.crmeb.com/static/images/favicon.ico
  deployCount: 23

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    sealos-db-provider-cr: crmeb-ywnvlics-mysql
    app.kubernetes.io/instance: crmeb-ywnvlics-mysql
    app.kubernetes.io/managed-by: kbcli
    cloud.sealos.io/deploy-on-sealos: crmeb-ywnvlics
  name: crmeb-ywnvlics-mysql

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    sealos-db-provider-cr: crmeb-ywnvlics-mysql
    app.kubernetes.io/instance: crmeb-ywnvlics-mysql
    app.kubernetes.io/managed-by: kbcli
    cloud.sealos.io/deploy-on-sealos: crmeb-ywnvlics
  name: crmeb-ywnvlics-mysql
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    sealos-db-provider-cr: crmeb-ywnvlics-mysql
    app.kubernetes.io/instance: crmeb-ywnvlics-mysql
    app.kubernetes.io/managed-by: kbcli
    cloud.sealos.io/deploy-on-sealos: crmeb-ywnvlics
  name: crmeb-ywnvlics-mysql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crmeb-ywnvlics-mysql
subjects:
  - kind: ServiceAccount
    name: crmeb-ywnvlics-mysql

---
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  finalizers:
    - cluster.kubeblocks.io/finalizer
  labels:
    clusterdefinition.kubeblocks.io/name: apecloud-mysql
    clusterversion.kubeblocks.io/name: ac-mysql-8.0.30
    cloud.sealos.io/deploy-on-sealos: crmeb-ywnvlics
  name: crmeb-ywnvlics-mysql
spec:
  affinity:
    nodeLabels: {}
    podAntiAffinity: Preferred
    tenancy: SharedNode
    topologyKeys: []
  clusterDefinitionRef: apecloud-mysql
  clusterVersionRef: ac-mysql-8.0.30
  componentSpecs:
    - componentDefRef: mysql
      monitor: true
      name: mysql
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 51Mi
      serviceAccountName: crmeb-ywnvlics-mysql
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 3Gi
            storageClassName: openebs-backup
  terminationPolicy: Delete
  tolerations: []

---
apiVersion: batch/v1
kind: Job
metadata:
  name: crmeb-ywnvlics-mysql-init
  labels:
    cloud.sealos.io/deploy-on-sealos: crmeb-ywnvlics
spec:
  completions: 1
  template:
    spec:
      containers:
        - name: mysql-init
          image: joseluisq/mysql-client:8.0.30
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: crmeb-ywnvlics-mysql-conn-credential
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crmeb-ywnvlics-mysql-conn-credential
                  key: password
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: crmeb-ywnvlics-mysql-conn-credential
                  key: host
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: crmeb-ywnvlics-mysql-conn-credential
                  key: port
          command:
            - /bin/sh
            - '-c'
            - >
              until mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER
              -p$MYSQL_PASSWORD -e 'CREATE DATABASE IF NOT EXISTS crmeb;'; do
              sleep 1; done
      restartPolicy: Never
  backoffLimit: 0
  ttlSecondsAfterFinished: 300

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    sealos-db-provider-cr: crmeb-ywnvlics-redis
    app.kubernetes.io/instance: crmeb-ywnvlics-redis
    app.kubernetes.io/managed-by: kbcli
    cloud.sealos.io/deploy-on-sealos: crmeb-ywnvlics
  name: crmeb-ywnvlics-redis

---
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  finalizers:
    - cluster.kubeblocks.io/finalizer
  labels:
    clusterdefinition.kubeblocks.io/name: redis
    clusterversion.kubeblocks.io/name: redis-7.0.6
    sealos-db-provider-cr: crmeb-ywnvlics-redis
    cloud.sealos.io/deploy-on-sealos: crmeb-ywnvlics
  annotations: {}
  name: crmeb-ywnvlics-redis
spec:
  affinity:
    nodeLabels: {}
    podAntiAffinity: Preferred
    tenancy: SharedNode
    topologyKeys: []
  clusterDefinitionRef: redis
  clusterVersionRef: redis-7.0.6
  componentSpecs:
    - componentDefRef: redis
      monitor: true
      name: redis
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 102Mi
      serviceAccountName: crmeb-ywnvlics-redis
      switchPolicy:
        type: Noop
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 3Gi
            storageClassName: openebs-backup
    - componentDefRef: redis-sentinel
      monitor: true
      name: redis-sentinel
      replicas: 1
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 100Mi
      serviceAccountName: crmeb-ywnvlics-redis
  terminationPolicy: Delete
  tolerations: []

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    sealos-db-provider-cr: crmeb-ywnvlics-redis
    app.kubernetes.io/instance: crmeb-ywnvlics-redis
    app.kubernetes.io/managed-by: kbcli
    cloud.sealos.io/deploy-on-sealos: crmeb-ywnvlics
  name: crmeb-ywnvlics-redis
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    sealos-db-provider-cr: crmeb-ywnvlics-redis
    app.kubernetes.io/instance: crmeb-ywnvlics-redis
    app.kubernetes.io/managed-by: kbcli
    cloud.sealos.io/deploy-on-sealos: crmeb-ywnvlics
  name: crmeb-ywnvlics-redis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crmeb-ywnvlics-redis
subjects:
  - kind: ServiceAccount
    name: crmeb-ywnvlics-redis
    namespace: ns-lg7dd5qb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crmeb-ywnvlics
  labels:
    cloud.sealos.io/deploy-on-sealos: crmeb-ywnvlics
data:
  vn-etcvn-nginxvn-confvn-dvn-defaultvn-conf: |-
    server {
        listen 80;
        index index.php index.html;
        server_name bz.crmeb.com;

        root /var/www/public;


        location / {
            # try_files $uri /index.php$is_args$args;
            if (!-e $request_filename){
                rewrite  ^(.*)$  /index.php?s=$1  last;   break;
            }
        }

        location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
        {
            expires      30d;
            error_log off;
            access_log /dev/null;
        }
        
        location ~ .*\.(js|css)?$
        {
            expires      12h;
            error_log off;
            access_log /dev/null; 
        }
        location /notice {
            proxy_pass http://127.0.0.1:20002;  
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-real-ip $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
        location /msg {
            proxy_pass http://127.0.0.1:20003/;  
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-real-ip $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
        
       

        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
        
       
    }

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crmeb-ywnvlics
  annotations:
    originImageName: ghcr.io/yangchuansheng/crmeb:v5.4.0
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: crmeb-ywnvlics
    app: crmeb-ywnvlics
    cloud.sealos.io/deploy-on-sealos: crmeb-ywnvlics
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: crmeb-ywnvlics
  selector:
    matchLabels:
      app: crmeb-ywnvlics
  template:
    metadata:
      labels:
        app: crmeb-ywnvlics
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      initContainers:
        - name: take-data-dir-ownership
          image: ghcr.io/yangchuansheng/crmeb:v5.4.0
          command:
            - /bin/sh
            - '-c'
            - >-
              if [ ! -f /tmp/index.html ]; then cp -rf /var/www/* /tmp/; cp -rf
              /var/www/.* /tmp/; mkdir /tmp/backup; chmod a+w /tmp/backup; chmod
              a+w /tmp/public; chmod a+w /tmp/runtime; chmod a+w /tmp/.env;
              chmod a+w /tmp/.version; chmod a+w /tmp/.constant; fi
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-varvn-www
              mountPath: /tmp
      containers:
        - name: crmeb-ywnvlics
          image: nginx:alpine3.20
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            requests:
              cpu: 10m
              memory: 12Mi
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-varvn-www
              mountPath: /var/www
            - name: vn-etcvn-nginxvn-confvn-dvn-defaultvn-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: ./etc/nginx/conf.d/default.conf
        - name: crmeb-ywnvlics-php
          image: ghcr.io/yangchuansheng/crmeb:v5.4.0
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            requests:
              cpu: 20m
              memory: 25Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - name: http
              protocol: TCP
              containerPort: 9000
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-varvn-www
              mountPath: /var/www
      volumes:
        - name: vn-etcvn-nginxvn-confvn-dvn-defaultvn-conf
          configMap:
            name: crmeb-ywnvlics
            items:
              - key: vn-etcvn-nginxvn-confvn-dvn-defaultvn-conf
                path: ./etc/nginx/conf.d/default.conf
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /var/www
          value: '1'
        name: vn-varvn-www
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: crmeb-ywnvlics
  labels:
    cloud.sealos.io/app-deploy-manager: crmeb-ywnvlics
    cloud.sealos.io/deploy-on-sealos: crmeb-ywnvlics
spec:
  ports:
    - port: 80
  selector:
    app: crmeb-ywnvlics

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crmeb-ywnvlics
  labels:
    cloud.sealos.io/app-deploy-manager: crmeb-ywnvlics
    cloud.sealos.io/app-deploy-manager-domain: crmeb-wyruqrnp
    cloud.sealos.io/deploy-on-sealos: crmeb-ywnvlics
  annotations:
    higress.io/response-header-control-remove: X-Frame-Options
    higress.io/response-header-control-update: >
      Content-Security-Policy "default-src * blob: data: *.sealoshzh.site
      sealoshzh.site; img-src * data: blob: resource: *.sealoshzh.site
      sealoshzh.site; connect-src * wss: blob: resource:; style-src 'self'
      'unsafe-inline' blob: *.sealoshzh.site sealoshzh.site resource:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: *.sealoshzh.site
      sealoshzh.site resource: *.baidu.com *.bdstatic.com; frame-src 'self'
      *.sealoshzh.site sealoshzh.site mailto: tel: weixin: mtt: *.baidu.com;
      frame-ancestors 'self' https://sealoshzh.site https://*.sealoshzh.site"

      X-Xss-Protection "1; mode=block"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: >
      more_clear_headers "X-Frame-Options:";

      more_set_headers "Content-Security-Policy: default-src * blob: data:
      *.sealoshzh.site sealoshzh.site; img-src * data: blob: resource:
      *.sealoshzh.site sealoshzh.site; connect-src * wss: blob: resource:;
      style-src 'self' 'unsafe-inline' blob: *.sealoshzh.site sealoshzh.site
      resource:; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:
      *.sealoshzh.site sealoshzh.site resource: *.baidu.com *.bdstatic.com;
      frame-src 'self' *.sealoshzh.site sealoshzh.site mailto: tel: weixin: mtt:
      *.baidu.com; frame-ancestors 'self' https://sealoshzh.site
      https://*.sealoshzh.site";

      more_set_headers "X-Xss-Protection: 1; mode=block";

      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: crmeb-wyruqrnp.sealoshzh.site
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: crmeb-ywnvlics
                port:
                  number: 80
  tls:
    - hosts:
        - crmeb-wyruqrnp.sealoshzh.site
      secretName: wildcard-cert

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: crmeb-ywnvlics
  labels:
    cloud.sealos.io/app-deploy-manager: crmeb-ywnvlics
    cloud.sealos.io/deploy-on-sealos: crmeb-ywnvlics
spec:
  data:
    url: https://crmeb-wyruqrnp.sealoshzh.site
  displayType: normal
  icon: https://www.crmeb.com/static/images/favicon.ico
  name: crmeb
  type: link
