apiVersion: app.sealos.io/v1
kind: Instance
metadata:
  name: chatgpt-on-wechat-pgjijhbu
  labels:
    cloud.sealos.io/deploy-on-sealos: chatgpt-on-wechat-pgjijhbu
spec:
  gitRepo: https://github.com/zhayujie/chatgpt-on-wechat
  templateType: inline
  categories:
    - ai
  defaults:
    app_name:
      type: string
      value: chatgpt-on-wechat-pgjijhbu
    app_host:
      type: string
      value: xzjlqaxa
  inputs:
    OPEN_AI_API_KEY:
      description: OpenAI API KEY
      type: string
      default: ''
      required: true
    OPEN_AI_API_BASE:
      description: OpenAI API 基础地址，带v1
      type: string
      default: https://api.openai.com/v1
      required: true
    MODEL:
      description: 模型名称
      type: string
      default: gpt-3.5-turbo
      required: true
    CHANNEL_TYPE:
      description: 渠道类型
      type: string
      default: wx
      required: true
    SINGLE_CHAT_PREFIX:
      description: 单聊前缀
      type: string
      default: '["bot"]'
      required: false
    SINGLE_CHAT_REPLY_PREFIX:
      description: 单聊回复前缀
      type: string
      default: '"[bot] "'
      required: false
    GROUP_CHAT_PREFIX:
      description: 群聊前缀
      type: string
      default: '["@bot"]'
      required: false
    GROUP_NAME_WHITE_LIST:
      description: 群聊白名单
      type: string
      default: '["ALL_GROUP"]'
      required: false
  title: chatgpt-on-wechat
  url: https://github.com/zhayujie/chatgpt-on-wechat
  author: zhayujie
  description: >-
    本项目是基于大模型的智能对话机器人，支持企业微信、微信公众号、飞书、钉钉接入，可选择GPT3.5/GPT4.0/Claude/文心一言/讯飞星火/通义千问/Gemini/LinkAI/ZhipuAI，能处理文本、语音和图片，通过插件访问操作系统和互联网等外部资源，支持基于自有知识库定制企业AI应用。
  readme: https://cdn.jsdelivr.net/gh/zhayujie/chatgpt-on-wechat@master/README.md
  icon: https://avatars.githubusercontent.com/u/26161723?v=4
  deployCount: 11

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-on-wechat-pgjijhbu
  annotations:
    originImageName: zhayujie/chatgpt-on-wechat:1.6.8
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: chatgpt-on-wechat-pgjijhbu
    app: chatgpt-on-wechat-pgjijhbu
    cloud.sealos.io/deploy-on-sealos: chatgpt-on-wechat-pgjijhbu
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: chatgpt-on-wechat-pgjijhbu
  template:
    metadata:
      labels:
        app: chatgpt-on-wechat-pgjijhbu
    spec:
      automountServiceAccountToken: false
      containers:
        - name: chatgpt-on-wechat-pgjijhbu
          image: zhayujie/chatgpt-on-wechat:1.6.8
          env:
            - name: OPEN_AI_API_KEY
              value: null
            - name: OPEN_AI_API_BASE
              value: https://api.openai.com/v1
            - name: MODEL
              value: gpt-3.5-turbo
            - name: CHANNEL_TYPE
              value: wx
            - name: DINGTALK_CLIENT_ID
              value: ''
            - name: DINGTALK_CLIENT_SECRET
              value: ''
            - name: PROXY
              value: ''
            - name: HOT_RELOAD
              value: 'False'
            - name: SINGLE_CHAT_PREFIX
              value: '["bot"]'
            - name: SINGLE_CHAT_REPLY_PREFIX
              value: '[bot] '
            - name: GROUP_CHAT_PREFIX
              value: '["@bot"]'
            - name: GROUP_NAME_WHITE_LIST
              value: '["ALL_GROUP"]'
            - name: IMAGE_CREATE_PREFIX
              value: '["画", "看", "找"]'
            - name: CONVERSATION_MAX_TOKENS
              value: '1000'
            - name: SPEECH_RECOGNITION
              value: 'False'
            - name: CHARACTER_DESC
              value: 你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。
            - name: SUBSCRIBE_MSG
              value: |
                感谢您的关注！
                这里是ChatGPT，可以自由对话。
                支持语音对话。
                支持图片输入。
                支持图片输出，画字开头的消息将按要求创作图片。
                支持tool、角色扮演和文字冒险等丰富的插件。
                输入{trigger_prefix}#help 查看详细指令。
            - name: EXPIRES_IN_SECONDS
              value: '3600'
            - name: USE_GLOBAL_PLUGIN_CONFIG
              value: 'True'
            - name: USE_LINKAI
              value: 'False'
            - name: LINKAI_API_KEY
              value: ''
            - name: LINKAI_APP_CODE
              value: ''
          resources:
            requests:
              cpu: 50m
              memory: 25Mi
            limits:
              cpu: 500m
              memory: 256Mi
          command: []
          args: []
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: chatgpt-on-wechat-pgjijhbu
  labels:
    cloud.sealos.io/app-deploy-manager: chatgpt-on-wechat-pgjijhbu
    cloud.sealos.io/deploy-on-sealos: chatgpt-on-wechat-pgjijhbu
spec:
  ports:
    - port: 80
  selector:
    app: chatgpt-on-wechat-pgjijhbu
