apiVersion: app.sealos.io/v1
kind: Instance
metadata:
  name: pageplug-hkzlhftn
  labels:
    cloud.sealos.io/deploy-on-sealos: pageplug-hkzlhftn
spec:
  gitRepo: https://github.com/cloudtogo/pageplug
  templateType: inline
  categories:
    - low-code
  defaults:
    app_host:
      type: string
      value: jdisxofi
    app_name:
      type: string
      value: pageplug-hkzlhftn
  inputs: null
  title: PagePlug
  url: https://lowcode.methodot.com/
  author: Sealos
  description: PagePlug 是 Appsmith 的中国化项目，是一个开源的、声明式的、可视化的前端低代码框架，可以用来制作 web 应用、微信小程序。
  readme: https://cdn.jsdelivr.net/gh/cloudtogo/pageplug@open-v1.9.35/README.md
  icon: >-
    https://cdn.jsdelivr.net/gh/cloudtogo/pageplug@open-v1.9.35/app/client/public/static/img/favicon-pageplug.ico
  deployCount: 3

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pageplug-hkzlhftn
  annotations:
    originImageName: cloudtogouser/pageplug-ce:v1.9.35
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: pageplug-hkzlhftn
    app: pageplug-hkzlhftn
    cloud.sealos.io/deploy-on-sealos: pageplug-hkzlhftn
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: pageplug-hkzlhftn
  selector:
    matchLabels:
      app: pageplug-hkzlhftn
  template:
    metadata:
      labels:
        app: pageplug-hkzlhftn
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      containers:
        - name: pageplug-hkzlhftn
          image: cloudtogouser/pageplug-ce:v1.9.35
          env: []
          resources:
            requests:
              cpu: 100m
              memory: 102Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          command: []
          args: []
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-appvn-data
              mountPath: /app/data
      volumes: []
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /app/data
          value: '1'
        name: vn-appvn-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: pageplug-hkzlhftn
  labels:
    cloud.sealos.io/app-deploy-manager: pageplug-hkzlhftn
    cloud.sealos.io/deploy-on-sealos: pageplug-hkzlhftn
spec:
  ports:
    - port: 80
  selector:
    app: pageplug-hkzlhftn

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pageplug-hkzlhftn
  labels:
    cloud.sealos.io/app-deploy-manager: pageplug-hkzlhftn
    cloud.sealos.io/app-deploy-manager-domain: jdisxofi
    cloud.sealos.io/deploy-on-sealos: pageplug-hkzlhftn
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: jdisxofi.sealoshzh.site
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: pageplug-hkzlhftn
                port:
                  number: 80
  tls:
    - hosts:
        - jdisxofi.sealoshzh.site
      secretName: wildcard-cert
