apiVersion: app.sealos.io/v1
kind: Instance
metadata:
  name: redisinsight-ymrvnnki
  labels:
    cloud.sealos.io/deploy-on-sealos: redisinsight-ymrvnnki
spec:
  gitRepo: https://github.com/RedisInsight/RedisInsight
  templateType: inline
  categories:
    - database
  defaults:
    app_name:
      type: string
      value: redisinsight-ymrvnnki
    app_host:
      type: string
      value: zjohficv
  inputs: {}
  title: RedisInsight
  url: https://redis.com/redis-enterprise/redis-insight/
  author: Sealos
  description: >-
    RedisInsight is a visual tool that provides capabilities to design, develop
    and optimize your Redis application. Query, analyse and interact with your
    Redis data.
  readme: https://cdn.jsdelivr.net/gh/RedisInsight/RedisInsight@main/README.md
  icon: >-
    https://cdn.jsdelivr.net/gh/RedisInsight/RedisInsight@main/redisinsight/ui/src/assets/img/logo.svg
  deployCount: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight-ymrvnnki
  annotations:
    originImageName: redislabs/redisinsight:2.52
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: redisinsight-ymrvnnki
    app: redisinsight-ymrvnnki
    cloud.sealos.io/deploy-on-sealos: redisinsight-ymrvnnki
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: redisinsight-ymrvnnki
  template:
    metadata:
      labels:
        app: redisinsight-ymrvnnki
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redisinsight-ymrvnnki
          image: redislabs/redisinsight:2.52
          env:
            - name: RITRUSTEDORIGINS
              value: https://zjohficv.sealoshzh.site
          resources:
            requests:
              cpu: 50m
              memory: 25Mi
            limits:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 5540
          imagePullPolicy: IfNotPresent
          volumeMounts: []
      volumes: []

---
apiVersion: v1
kind: Service
metadata:
  name: redisinsight-ymrvnnki
  labels:
    cloud.sealos.io/app-deploy-manager: redisinsight-ymrvnnki
    cloud.sealos.io/deploy-on-sealos: redisinsight-ymrvnnki
spec:
  ports:
    - port: 5540
  selector:
    app: redisinsight-ymrvnnki

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redisinsight-ymrvnnki
  labels:
    cloud.sealos.io/app-deploy-manager: redisinsight-ymrvnnki
    cloud.sealos.io/app-deploy-manager-domain: zjohficv
    cloud.sealos.io/deploy-on-sealos: redisinsight-ymrvnnki
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: zjohficv.sealoshzh.site
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: redisinsight-ymrvnnki
                port:
                  number: 5540
  tls:
    - hosts:
        - zjohficv.sealoshzh.site
      secretName: wildcard-cert
