apiVersion: app.sealos.io/v1
kind: Instance
metadata:
  name: ubuntu-sshd-hcjgikuz
  labels:
    cloud.sealos.io/deploy-on-sealos: ubuntu-sshd-hcjgikuz
spec:
  gitRepo: https://github.com/takeyamajp/docker-ubuntu-sshd
  templateType: inline
  categories:
    - tool
  defaults:
    app_name:
      type: string
      value: ubuntu-sshd-hcjgikuz
  inputs:
    ROOT_PASSWORD:
      description: root password
      type: string
      default: root@qmywad
      required: true
  title: docker-ubuntu-sshd
  url: https://github.com/takeyamajp/docker-ubuntu-sshd
  author: Sealos
  description: Ubuntu image with SSH & SFTP
  readme: https://github.com/takeyamajp/docker-ubuntu-sshd/blob/master/README.md
  icon: https://avatars.githubusercontent.com/u/11237572?s=48&v=4
  deployCount: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-sshd-hcjgikuz
  annotations:
    originImageName: takeyamajp/ubuntu-sshd:ubuntu22.04
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ubuntu-sshd-hcjgikuz
    app: ubuntu-sshd-hcjgikuz
    cloud.sealos.io/deploy-on-sealos: ubuntu-sshd-hcjgikuz
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ubuntu-sshd-hcjgikuz
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: ubuntu-sshd-hcjgikuz
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ubuntu-sshd
          image: takeyamajp/ubuntu-sshd:ubuntu22.04
          resources:
            requests:
              cpu: 100m
              memory: 102Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          command: []
          args: []
          env:
            - name: ROOT_PASSWORD
              value: root@qmywad
          ports:
            - containerPort: 22
          imagePullPolicy: IfNotPresent
          volumeMounts: []
      volumes: []

---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-sshd-hcjgikuz
  labels:
    cloud.sealos.io/app-deploy-manager: ubuntu-sshd-hcjgikuz
    cloud.sealos.io/deploy-on-sealos: ubuntu-sshd-hcjgikuz
spec:
  type: NodePort
  ports:
    - port: 22
      targetPort: 22
  selector:
    app: ubuntu-sshd-hcjgikuz
