apiVersion: app.sealos.io/v1
kind: Instance
metadata:
  name: code-server-fetyatle
  labels:
    cloud.sealos.io/deploy-on-sealos: code-server-fetyatle
spec:
  gitRepo: https://github.com/coder/code-server
  templateType: inline
  categories:
    - tool
  defaults:
    app_host:
      type: string
      value: fvrqvaif
    app_name:
      type: string
      value: code-server-fetyatle
    time_zone:
      type: string
      value: Asia/Shanghai
  inputs:
    PASSWORD:
      description: Access Password
      type: string
      default: sealos123
      required: true
  title: code-server
  url: https://github.com/coder/code-server
  author: Sealos
  description: VS Code in the browser
  readme: https://cdn.jsdelivr.net/gh/coder/code-server@main/docs/README.md
  icon: >-
    https://cdn.jsdelivr.net/gh/coder/code-server@main/src/browser/media/favicon.svg

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: code-server-fetyatle
  annotations:
    originImageName: codercom/code-server:4.90.3-39
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: code-server-fetyatle
    app: code-server-fetyatle
    cloud.sealos.io/deploy-on-sealos: code-server-fetyatle
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: code-server-fetyatle
  selector:
    matchLabels:
      app: code-server-fetyatle
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: code-server-fetyatle
    spec:
      automountServiceAccountToken: false
      containers:
        - name: code-server-fetyatle
          image: codercom/code-server:4.90.3-39
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: PASSWORD
              value: sealos123
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          command:
            - /bin/sh
            - '-c'
          args:
            - >
              mkdir -p /home/coder/workspace && /usr/bin/entrypoint.sh
              --bind-addr 0.0.0.0:8080 /home/coder/workspace
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-homevn-coder
              mountPath: /home/coder
      volumes: []
      securityContext:
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /home/coder
          value: '1'
        name: vn-homevn-coder
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: code-server-fetyatle
  labels:
    cloud.sealos.io/app-deploy-manager: code-server-fetyatle
    cloud.sealos.io/deploy-on-sealos: code-server-fetyatle
spec:
  ports:
    - port: 8080
  selector:
    app: code-server-fetyatle

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server-fetyatle
  labels:
    cloud.sealos.io/app-deploy-manager: code-server-fetyatle
    cloud.sealos.io/app-deploy-manager-domain: fvrqvaif
    cloud.sealos.io/deploy-on-sealos: code-server-fetyatle
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: fvrqvaif.sealoshzh.site
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: code-server-fetyatle
                port:
                  number: 8080
  tls:
    - hosts:
        - fvrqvaif.sealoshzh.site
      secretName: wildcard-cert

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: code-server-fetyatle
  labels:
    cloud.sealos.io/deploy-on-sealos: code-server-fetyatle
spec:
  data:
    url: https://fvrqvaif.sealoshzh.site
  displayType: normal
  icon: https://avatars.githubusercontent.com/u/95932066?s=96&v=4
  name: Code Server
  type: iframe
