apiVersion: app.sealos.io/v1
kind: Instance
metadata:
  name: plausible-aitbgmfk
  labels:
    cloud.sealos.io/deploy-on-sealos: plausible-aitbgmfk
spec:
  gitRepo: https://github.com/plausible/analytics
  templateType: inline
  categories:
    - tool
  defaults:
    app_host:
      type: string
      value: ysxdydwm
    app_name:
      type: string
      value: plausible-aitbgmfk
  inputs:
    CLICKHOUSE_USER:
      description: clickhouse user name
      type: string
      default: ''
      required: true
    CLICKHOUSE_PASSWORD:
      description: clickhouse password
      type: string
      default: ''
      required: true
    DISABLE_REGISTRATION:
      description: true or false
      type: string
      default: ''
      required: true
    SECRET_KEY_BASE:
      description: >-
        You can generate it using the following command: openssl rand -base64 64
        | tr -d '

        ' ; echo
      type: string
      default: >-
        FhNHzoWJyoQgT21RsFQG+KUzJ/o5YbKsszc6CMOArA0OXxjZ763oCGiItOPlKJAfIQO0uov8xt8p5k+MqtmtOQ==
      required: true
  title: plausible
  url: https://github.com/plausible/analytics
  author: Sealos
  description: >-
    Simple, open-source, lightweight (< 1 KB) and privacy-friendly web analytics
    alternative to Google Analytics.
  readme: https://cdn.jsdelivr.net/gh/plausible/analytics@master/README.md
  icon: >-
    https://cdn.jsdelivr.net/gh/plausible/docs@master/static/img/plausible-analytics-icon-top.png
  deployCount: 1

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    sealos-db-provider-cr: plausible-aitbgmfk-db
    app.kubernetes.io/instance: plausible-aitbgmfk-db
    app.kubernetes.io/managed-by: kbcli
    cloud.sealos.io/deploy-on-sealos: plausible-aitbgmfk
  name: plausible-aitbgmfk-db

---
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  finalizers:
    - cluster.kubeblocks.io/finalizer
  labels:
    clusterdefinition.kubeblocks.io/name: postgresql
    clusterversion.kubeblocks.io/name: postgresql-14.8.0
    sealos-db-provider-cr: plausible-aitbgmfk-db
    cloud.sealos.io/deploy-on-sealos: plausible-aitbgmfk
  annotations: {}
  name: plausible-aitbgmfk-db
spec:
  affinity:
    nodeLabels: {}
    podAntiAffinity: Preferred
    tenancy: SharedNode
    topologyKeys: []
  clusterDefinitionRef: postgresql
  clusterVersionRef: postgresql-14.8.0
  componentSpecs:
    - componentDefRef: postgresql
      monitor: true
      name: postgresql
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 50m
          memory: 50Mi
      serviceAccountName: plausible-aitbgmfk-db
      switchPolicy:
        type: Noop
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: openebs-backup
  terminationPolicy: Delete
  tolerations: []

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    sealos-db-provider-cr: plausible-aitbgmfk-db
    app.kubernetes.io/instance: plausible-aitbgmfk-db
    app.kubernetes.io/managed-by: kbcli
    cloud.sealos.io/deploy-on-sealos: plausible-aitbgmfk
  name: plausible-aitbgmfk-db
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    sealos-db-provider-cr: plausible-aitbgmfk-db
    app.kubernetes.io/instance: plausible-aitbgmfk-db
    app.kubernetes.io/managed-by: kbcli
    cloud.sealos.io/deploy-on-sealos: plausible-aitbgmfk
  name: plausible-aitbgmfk-db
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: plausible-aitbgmfk-db
subjects:
  - kind: ServiceAccount
    name: plausible-aitbgmfk-db

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plausible-aitbgmfk-events-db
  labels:
    cloud.sealos.io/app-deploy-manager: plausible-aitbgmfk-events-db
    app: plausible-aitbgmfk-events-db
    cloud.sealos.io/deploy-on-sealos: plausible-aitbgmfk
data:
  vn-etcvn-clickhouse-servervn-configvn-dvn-loggingvn-xml: |-
    <clickhouse>

        <!-- disable IPv6 -->
        <listen_host>0.0.0.0</listen_host>

        <logger>
            <level>warning</level>
            <console>true</console>
        </logger>

        <!-- Stop all the unnecessary logging -->
        <query_thread_log remove="remove"/>
        <query_log remove="remove"/>
        <text_log remove="remove"/>
        <trace_log remove="remove"/>
        <metric_log remove="remove"/>
        <asynchronous_metric_log remove="remove"/>
        <session_log remove="remove"/>
        <part_log remove="remove"/>
    </clickhouse>
  vn-etcvn-clickhouse-servervn-usersvn-dvn-loggingvn-xml: |-
    <clickhouse>
        <profiles>
            <default>
                <log_queries>0</log_queries>
                <log_query_threads>0</log_query_threads>
            </default>
        </profiles>
    </clickhouse>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plausible-aitbgmfk-events-db
  annotations:
    originImageName: clickhouse/clickhouse-server:23.3.7.5-alpine
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: plausible-aitbgmfk-events-db
    app: plausible-aitbgmfk-events-db
    cloud.sealos.io/deploy-on-sealos: plausible-aitbgmfk
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: plausible-aitbgmfk-events-db
  serviceName: plausible-aitbgmfk-events-db
  template:
    metadata:
      labels:
        app: plausible-aitbgmfk-events-db
    spec:
      automountServiceAccountToken: false
      containers:
        - name: plausible-aitbgmfk-events-db
          image: clickhouse/clickhouse-server:23.3.7.5-alpine
          env:
            - name: CLICKHOUSE_DB
              value: plausible
            - name: CLICKHOUSE_LISTEN_HOST
              value: 0.0.0.0
            - name: CLICKHOUSE_USER
              value: null
            - name: CLICKHOUSE_PASSWORD
              value: null
          resources:
            requests:
              cpu: 50m
              memory: 102Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          command: []
          args: []
          ports:
            - containerPort: 8123
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-etcvn-clickhouse-servervn-configvn-dvn-loggingvn-xml
              mountPath: /etc/clickhouse-server/config.d/logging.xml
              subPath: ./etc/clickhouse-server/config.d/logging.xml
            - name: vn-etcvn-clickhouse-servervn-usersvn-dvn-loggingvn-xml
              mountPath: /etc/clickhouse-server/users.d/logging.xml
              subPath: ./etc/clickhouse-server/users.d/logging.xml
            - name: vn-varvn-libvn-clickhouse
              mountPath: /var/lib/clickhouse
      volumes:
        - name: vn-etcvn-clickhouse-servervn-configvn-dvn-loggingvn-xml
          configMap:
            name: plausible-aitbgmfk-events-db
            items:
              - key: vn-etcvn-clickhouse-servervn-configvn-dvn-loggingvn-xml
                path: ./etc/clickhouse-server/config.d/logging.xml
        - name: vn-etcvn-clickhouse-servervn-usersvn-dvn-loggingvn-xml
          configMap:
            name: plausible-aitbgmfk-events-db
            items:
              - key: vn-etcvn-clickhouse-servervn-usersvn-dvn-loggingvn-xml
                path: ./etc/clickhouse-server/users.d/logging.xml
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /var/lib/clickhouse
          value: '5'
        name: vn-varvn-libvn-clickhouse
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: plausible-aitbgmfk-events-db
  labels:
    cloud.sealos.io/app-deploy-manager: plausible-aitbgmfk-events-db
    cloud.sealos.io/deploy-on-sealos: plausible-aitbgmfk
spec:
  ports:
    - port: 8123
  selector:
    app: plausible-aitbgmfk-events-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible-aitbgmfk
  annotations:
    originImageName: plausible/analytics:v2.0
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: plausible-aitbgmfk
    app: plausible-aitbgmfk
    cloud.sealos.io/deploy-on-sealos: plausible-aitbgmfk
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: plausible-aitbgmfk
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: plausible-aitbgmfk
    spec:
      automountServiceAccountToken: false
      containers:
        - name: plausible-aitbgmfk
          image: plausible/analytics:v2.0
          env:
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plausible-aitbgmfk-db-conn-credential
                  key: password
            - name: DATABASE_URL
              value: >-
                postgres://postgres:$(PG_PASSWORD)@plausible-aitbgmfk-db-postgresql:5432/plausible
            - name: CLICKHOUSE_DATABASE_URL
              value: http://:@plausible-aitbgmfk-events-db:8123/plausible
            - name: DISABLE_REGISTRATION
              value: null
            - name: BASE_URL
              value: https://ysxdydwm.sealoshzh.site
            - name: SECRET_KEY_BASE
              value: >-
                FhNHzoWJyoQgT21RsFQG+KUzJ/o5YbKsszc6CMOArA0OXxjZ763oCGiItOPlKJAfIQO0uov8xt8p5k+MqtmtOQ==
          resources:
            requests:
              cpu: 100m
              memory: 102Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          command:
            - sh
            - '-c'
          args:
            - >-
              sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db
              migrate && /entrypoint.sh run
          ports:
            - containerPort: 8000
          imagePullPolicy: IfNotPresent
          volumeMounts: []
      volumes: []

---
apiVersion: v1
kind: Service
metadata:
  name: plausible-aitbgmfk
  labels:
    cloud.sealos.io/app-deploy-manager: plausible-aitbgmfk
    cloud.sealos.io/deploy-on-sealos: plausible-aitbgmfk
spec:
  ports:
    - port: 8000
  selector:
    app: plausible-aitbgmfk

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plausible-aitbgmfk
  labels:
    cloud.sealos.io/app-deploy-manager: plausible-aitbgmfk
    cloud.sealos.io/app-deploy-manager-domain: ysxdydwm
    cloud.sealos.io/deploy-on-sealos: plausible-aitbgmfk
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ysxdydwm.sealoshzh.site
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: plausible-aitbgmfk
                port:
                  number: 8000
  tls:
    - hosts:
        - ysxdydwm.sealoshzh.site
      secretName: wildcard-cert
