apiVersion: app.sealos.io/v1
kind: Instance
metadata:
  name: metabase-eviegfvr
  labels:
    cloud.sealos.io/deploy-on-sealos: metabase-eviegfvr
spec:
  gitRepo: https://github.com/metabase/metabase
  templateType: inline
  categories:
    - database
    - low-code
  defaults:
    app_host:
      type: string
      value: weizokvc
    app_name:
      type: string
      value: metabase-eviegfvr
  inputs: null
  title: metabase
  url: metabase.com
  author: Sealos
  description: >-
    The simplest, fastest way to get business intelligence and analytics to
    everyone in your company 😋
  readme: https://cdn.jsdelivr.net/gh/metabase/metabase@master/README.md
  icon: https://www.metabase.com/images/logo.svg
  deployCount: 1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metabase-eviegfvr
  annotations:
    originImageName: metabase/metabase:v0.50.17
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: metabase-eviegfvr
    app: metabase-eviegfvr
    cloud.sealos.io/deploy-on-sealos: metabase-eviegfvr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: metabase-eviegfvr
  selector:
    matchLabels:
      app: metabase-eviegfvr
  template:
    metadata:
      labels:
        app: metabase-eviegfvr
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      containers:
        - name: metabase-eviegfvr
          image: metabase/metabase:v0.50.17
          env:
            - name: MB_DB_TYPE
              value: postgres
            - name: MB_DB_DBNAME
              value: metabaseappdb
            - name: MB_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: metabase-eviegfvr-pg-conn-credential
                  key: port
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: metabase-eviegfvr-pg-conn-credential
                  key: username
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: metabase-eviegfvr-pg-conn-credential
                  key: password
            - name: MB_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: metabase-eviegfvr-pg-conn-credential
                  key: host
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-plugins
              mountPath: /plugins
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /plugins
          value: '1'
        name: vn-plugins
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: metabase-eviegfvr
  labels:
    cloud.sealos.io/app-deploy-manager: metabase-eviegfvr
    cloud.sealos.io/deploy-on-sealos: metabase-eviegfvr
spec:
  ports:
    - port: 3000
  selector:
    app: metabase-eviegfvr

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase-eviegfvr
  labels:
    cloud.sealos.io/app-deploy-manager: metabase-eviegfvr
    cloud.sealos.io/app-deploy-manager-domain: weizokvc
    cloud.sealos.io/deploy-on-sealos: metabase-eviegfvr
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: weizokvc.sealoshzh.site
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: metabase-eviegfvr
                port:
                  number: 3000
  tls:
    - hosts:
        - weizokvc.sealoshzh.site
      secretName: wildcard-cert

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    sealos-db-provider-cr: metabase-eviegfvr-pg
    app.kubernetes.io/instance: metabase-eviegfvr-pg
    app.kubernetes.io/managed-by: kbcli
    cloud.sealos.io/deploy-on-sealos: metabase-eviegfvr
  name: metabase-eviegfvr-pg

---
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  finalizers:
    - cluster.kubeblocks.io/finalizer
  labels:
    clusterdefinition.kubeblocks.io/name: postgresql
    clusterversion.kubeblocks.io/name: postgresql-14.8.0
    sealos-db-provider-cr: metabase-eviegfvr-pg
    cloud.sealos.io/deploy-on-sealos: metabase-eviegfvr
  annotations: {}
  name: metabase-eviegfvr-pg
spec:
  affinity:
    nodeLabels: {}
    podAntiAffinity: Preferred
    tenancy: SharedNode
    topologyKeys: []
  clusterDefinitionRef: postgresql
  clusterVersionRef: postgresql-14.8.0
  componentSpecs:
    - componentDefRef: postgresql
      monitor: true
      name: postgresql
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 102Mi
      serviceAccountName: metabase-eviegfvr-pg
      switchPolicy:
        type: Noop
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: openebs-backup
  terminationPolicy: Delete
  tolerations: []

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    sealos-db-provider-cr: metabase-eviegfvr-pg
    app.kubernetes.io/instance: metabase-eviegfvr-pg
    app.kubernetes.io/managed-by: kbcli
    cloud.sealos.io/deploy-on-sealos: metabase-eviegfvr
  name: metabase-eviegfvr-pg
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    sealos-db-provider-cr: metabase-eviegfvr-pg
    app.kubernetes.io/instance: metabase-eviegfvr-pg
    app.kubernetes.io/managed-by: kbcli
    cloud.sealos.io/deploy-on-sealos: metabase-eviegfvr
  name: metabase-eviegfvr-pg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metabase-eviegfvr-pg
subjects:
  - kind: ServiceAccount
    name: metabase-eviegfvr-pg

---
apiVersion: batch/v1
kind: Job
metadata:
  name: metabase-eviegfvr-init
  labels:
    cloud.sealos.io/deploy-on-sealos: metabase-eviegfvr
spec:
  completions: 1
  template:
    spec:
      containers:
        - name: pgsql-init
          image: senzing/postgresql-client:2.2.4
          env:
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: metabase-eviegfvr-pg-conn-credential
                  key: password
            - name: DATABASE_URL
              value: >-
                postgresql://postgres:$(PG_PASSWORD)@metabase-eviegfvr-pg-postgresql..svc:5432
          command:
            - /bin/sh
            - '-c'
            - >
              until psql ${DATABASE_URL} -c 'CREATE DATABASE metabaseappdb;'
              &>/dev/null; do sleep 1; done
      restartPolicy: Never
  backoffLimit: 0
  ttlSecondsAfterFinished: 300

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: metabase-eviegfvr
  labels:
    cloud.sealos.io/app-deploy-manager: metabase-eviegfvr
    cloud.sealos.io/deploy-on-sealos: metabase-eviegfvr
spec:
  data:
    url: https://weizokvc.sealoshzh.site
  displayType: normal
  icon: https://www.metabase.com/images/logo.svg
  name: metabase
  type: link
