apiVersion: app.sealos.io/v1
kind: Instance
metadata:
  name: alist-dbogfsya
  labels:
    cloud.sealos.io/deploy-on-sealos: alist-dbogfsya
spec:
  gitRepo: https://github.com/alist-org/alist
  templateType: inline
  categories:
    - tool
  defaults:
    app_host:
      type: string
      value: afzaorhu
    app_name:
      type: string
      value: alist-dbogfsya
  inputs: null
  title: alist
  url: https://github.com/alist-org/alist
  author: 孤城落寞
  description: >-
    A file list/WebDAV program that supports multiple storages, powered by Gin
    and Solidjs.
  readme: https://cdn.jsdelivr.net/gh/alist-org/alist@main/README_cn.md
  icon: https://cdn.jsdelivr.net/gh/alist-org/logo@main/logo.svg
  deployCount: 31

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alist-dbogfsya
  annotations:
    originImageName: xhofe/alist-aria2:latest
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: alist-dbogfsya
    app: alist-dbogfsya
    cloud.sealos.io/deploy-on-sealos: alist-dbogfsya
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: alist-dbogfsya
  selector:
    matchLabels:
      app: alist-dbogfsya
  template:
    metadata:
      labels:
        app: alist-dbogfsya
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      containers:
        - name: alist-dbogfsya
          image: xhofe/alist-aria2:latest
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            requests:
              cpu: 20m
              memory: 12Mi
            limits:
              cpu: 200m
              memory: 128Mi
          command: []
          args: []
          ports:
            - containerPort: 5244
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-data
              mountPath: /opt/alist/data
      volumes: []
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /opt/alist/data
          value: '1'
        name: vn-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: alist-dbogfsya
  labels:
    cloud.sealos.io/app-deploy-manager: alist-dbogfsya
    cloud.sealos.io/deploy-on-sealos: alist-dbogfsya
spec:
  ports:
    - port: 5244
  selector:
    app: alist-dbogfsya

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alist-dbogfsya
  labels:
    cloud.sealos.io/app-deploy-manager: alist-dbogfsya
    cloud.sealos.io/app-deploy-manager-domain: afzaorhu
    cloud.sealos.io/deploy-on-sealos: alist-dbogfsya
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: afzaorhu.sealoshzh.site
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: alist-dbogfsya
                port:
                  number: 5244
  tls:
    - hosts:
        - afzaorhu.sealoshzh.site
      secretName: wildcard-cert

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: alist-dbogfsya
  labels:
    cloud.sealos.io/app-deploy-manager: alist-dbogfsya
    cloud.sealos.io/deploy-on-sealos: alist-dbogfsya
spec:
  data:
    url: https://afzaorhu.sealoshzh.site
  displayType: normal
  icon: https://raw.githubusercontent.com/alist-org/logo/main/logo.svg
  name: alist-dbogfsya
  type: iframe
