apiVersion: app.sealos.io/v1
kind: Instance
metadata:
  name: influxdb-cmmcrzld
  labels:
    cloud.sealos.io/deploy-on-sealos: influxdb-cmmcrzld
spec:
  templateType: inline
  categories:
    - database
  defaults:
    app_host:
      type: string
      value: ytwwkasi
    app_name:
      type: string
      value: influxdb-cmmcrzld
  inputs: null
  title: influxdb
  author: Sealos
  description: >-
    Real-time insights from any time series data with a single, purpose-built
    database. Run at any scale in any environment in the cloud, on-premises, or
    at the edge.
  readme: ''
  icon: https://avatars.githubusercontent.com/u/5713248?s=200&v=4

---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-cmmcrzld
  labels:
    cloud.sealos.io/app-deploy-manager: influxdb-cmmcrzld
    app.kubernetes.io/instance: influxdb-cmmcrzld
    app.kubernetes.io/name: influxdb-cmmcrzld
    app.kubernetes.io/version: 2.7.5
    cloud.sealos.io/deploy-on-sealos: influxdb-cmmcrzld
type: Opaque
data:
  admin-user-password: cGFzc3cwcmQ=
  admin-user-token: dDBrZW4=

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-cmmcrzld
  labels:
    cloud.sealos.io/app-deploy-manager: influxdb-cmmcrzld
    cloud.sealos.io/deploy-on-sealos: influxdb-cmmcrzld
spec:
  ports:
    - port: 8086
      targetPort: 8086
      name: http
    - port: 8088
      targetPort: 8088
      name: rpc
  selector:
    app: influxdb-cmmcrzld

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: influxdb-cmmcrzld
  labels:
    cloud.sealos.io/app-deploy-manager: influxdb-cmmcrzld
    app.kubernetes.io/instance: influxdb-cmmcrzld
    app.kubernetes.io/name: influxdb-cmmcrzld
    app.kubernetes.io/version: 2.7.5
    app.kubernetes.io/component: influxdb-cmmcrzld
    cloud.sealos.io/deploy-on-sealos: influxdb-cmmcrzld
automountServiceAccountToken: false

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb-cmmcrzld
  annotations:
    originImageName: nginx
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
    deploy.cloud.sealos.io/resize: 5Gi
  labels:
    cloud.sealos.io/app-deploy-manager: influxdb-cmmcrzld
    app: influxdb-cmmcrzld
    cloud.sealos.io/deploy-on-sealos: influxdb-cmmcrzld
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: influxdb-cmmcrzld
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  minReadySeconds: 10
  serviceName: influxdb-cmmcrzld
  template:
    metadata:
      labels:
        app: influxdb-cmmcrzld
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: influxdb-cmmcrzld
                    app.kubernetes.io/name: influxdb-cmmcrzld
                    app.kubernetes.io/component: influxdb-cmmcrzld
                topologyKey: kubernetes.io/hostname
              weight: 1
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      serviceAccountName: influxdb-cmmcrzld
      containers:
        - name: influxdb
          image: docker.io/bitnami/influxdb:2.7.5-debian-12-r13
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: BITNAMI_DEBUG
              value: 'false'
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: INFLUXDB_HTTP_AUTH_ENABLED
              value: 'true'
            - name: INFLUXDB_CREATE_USER_TOKEN
              value: 'no'
            - name: INFLUXDB_ADMIN_USER
              value: admin
            - name: INFLUXDB_ADMIN_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-cmmcrzld
                  key: admin-user-password
            - name: INFLUXDB_ADMIN_USER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-cmmcrzld
                  key: admin-user-token
            - name: INFLUXDB_ADMIN_BUCKET
              value: primary
            - name: INFLUXDB_ADMIN_ORG
              value: primary
          envFrom: null
          ports:
            - name: http
              containerPort: 8086
              protocol: TCP
            - name: rpc
              containerPort: 8088
              protocol: TCP
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 180
            periodSeconds: 45
            successThreshold: 1
            timeoutSeconds: 30
            exec:
              command:
                - bash
                - '-c'
                - |
                  . /opt/bitnami/scripts/libinfluxdb.sh
                  influxdb_env
                  export INFLUX_USERNAME="$INFLUXDB_ADMIN_USER"
                  export INFLUX_PASSWORD="$INFLUXDB_ADMIN_USER_PASSWORD"
                  timeout 29s influx ping --host http://$POD_IP:8086
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 45
            successThreshold: 1
            timeoutSeconds: 30
            exec:
              command:
                - bash
                - '-c'
                - |
                  . /opt/bitnami/scripts/libinfluxdb.sh
                  influxdb_env
                  export INFLUX_USERNAME="$INFLUXDB_ADMIN_USER"
                  export INFLUX_PASSWORD="$INFLUXDB_ADMIN_USER_PASSWORD"
                  timeout 29s influx ping --host http://$POD_IP:8086
          resources:
            limits:
              cpu: 1000m
              ephemeral-storage: 1024Mi
              memory: 1024Mi
            requests:
              cpu: 100m
              ephemeral-storage: 50Mi
              memory: 128Mi
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/influxdb/etc
              subPath: app-conf-dir
            - name: vn-bitnamivn-influxdb
              mountPath: /bitnami/influxdb
      volumes:
        - name: empty-dir
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /bitnami/influxdb
          value: '5'
        name: vn-bitnamivn-influxdb
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: network-eadkuyljeayo
  labels:
    cloud.sealos.io/app-deploy-manager: influxdb-cmmcrzld
    cloud.sealos.io/app-deploy-manager-domain: ytwwkasi
    cloud.sealos.io/deploy-on-sealos: influxdb-cmmcrzld
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
spec:
  rules:
    - host: ytwwkasi.sealoshzh.site
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: influxdb-cmmcrzld
                port:
                  number: 8086
  tls:
    - hosts:
        - ytwwkasi.sealoshzh.site
      secretName: wildcard-cert
